# Generated by Django 2.2.3 on 2019-09-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noise_Pollution', '0002_auto_20190725_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensore',
            name='key',
            field=models.CharField(default='000000000000000', max_length=15),
        ),
    ]
