# Generated by Django 2.2.3 on 2019-10-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Noise_Pollution', '0004_stanza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensore',
            name='location',
        ),
    ]
