# Generated by Django 2.2.3 on 2019-10-09 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Noise_Pollution', '0005_remove_sensore_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensore',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Noise_Pollution.Stanza'),
        ),
    ]
