# Generated by Django 2.2.3 on 2019-10-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noise_Pollution', '0006_sensore_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensore',
            name='authenticated',
            field=models.BooleanField(default=0),
        ),
    ]
